runtime: python312  # replace with your Python version
entrypoint: gunicorn -b :$PORT main:app  # replace 'main:app' with your app's entry point

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: 'SciWeb_API_secret.json'

# set GOOGLE_APPLICATION_CREDENTIALS=/static/SciWeb_API_secret.json